# Generated by Django 4.2.10 on 2024-04-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBMS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordetails',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
