# Generated by Django 4.2.10 on 2024-04-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBMS_APP', '0002_alter_donordetails_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorderdetails',
            name='additional',
        ),
        migrations.AddField(
            model_name='customerorderdetails',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
