# Generated by Django 4.2.10 on 2024-04-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBMS_APP', '0003_remove_customerorderdetails_additional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderdetails',
            name='razorpay_order_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
