# Generated by Django 4.2.10 on 2024-05-03 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BBMS_APP', '0004_customerorderdetails_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloginsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
