# Generated by Django 4.2.10 on 2024-05-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBMS_APP', '0005_alter_customerloginsession_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloginsession',
            name='session_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
